dist: trusty

language: node_js

node_js:
  - lts/*

before_script:
  - rm -rf public || exit 0

install:
  - yarn

script:
  - yarn deploy
  - echo 'coldstone.fun' > public/CNAME

cache: yarn

deploy:
  provider: pages
  skip-cleanup: true
  local-dir: public
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
